### ISSUE TITLE
Unable to add note

### ISSUE THREAD

**Issue by dokmanc** [cyberbiont/vscode-sidenotes#3]
1. I disabled all of my extensions excel for SideNotes. 
2. I restarted VS Code
3. I added an annotation. It added a comment in my code and a matchging M<D file but did not open the MD file to the right.
4. The developer console shows the following. If I type directly into the note file, I see no tooltip when hovering over anything need the note comment.

```
extensionNls.ts:51 [linenote]: Couldn't find message for key configuration.automaticallyDeleteInterval.description.
v @ extensionNls.ts:51
TaskQueue.ts:93 task queue exceeded allotted deadline by 37ms
_process @ TaskQueue.ts:93
console.ts:137 [Extension Host] TypeError: Cannot destructure property 'ranges' of 'this.scanner.scanLine(...)' as it is undefined.
	at a.SidenoteFactory.build (c:\Users\C39293\.vscode\extensions\cyberbiont.vscode-sidenotes-1.0.0\dist\extension.js:8:30620)
	at async a.DictionaryRepository.create (c:\Users\C39293\.vscode\extensions\cyberbiont.vscode-sidenotes-1.0.0\dist\extension.js:8:27122)
	at async a.default.run (c:\Users\C39293\.vscode\extensions\cyberbiont.vscode-sidenotes-1.0.0\dist\extension.js:8:934)
	at async r.h (c:\Users\C39293\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:82736)
lo
g.ts:421  INFO [perf] Render performance baseline is 277ms
```

**Comment by cyberbiont** [comment]
Very kind of you to leave 1 star rating on Marketplace before even giving the developer time to investigate.

It's the first time I hear about this problem (nor anybody else complained about it) so I certainly can't tell you what's it about in a sec.

**Comment by dokmanc** [comment]
Yaroslav,

Well, most people don't report issues. Two other people did, one in Sept 2021 and the other in April of 2023. Your response to both was that you didn't have time to look into it.  I also got the issue on multiple PCs with no other extensions enabled. My conclusion was that this extension probably worked at one time but was no longer compatible with the latest version of VS Code and given the lack of activity in the repository, it looked like you lost interest in this or, as you said in April, don't have the time. 

I wanted to delete my review but that functionality doesn't exist. Instead, I modified my rating to 3 in optimism that it might one day be fixed. Meanwhile, I'll try to offer you whatever info you need to fix the issue.

In my attempt to get the extension to work, I have tried to disable other extensions in the workspace and enable SideNote in the workspace. I tried enabling SideNote globally. When I did, I saw the following error in the console.


```

FileSystem#$watch(): failed to stat a resource for file watching (extension: cyberbiont.vscode-sidenotes, path: file:///d:/GitHub/.sidenotes, recursive: true, session: 0.5988611814114806): EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'd:\GitHub\.sidenotes'
workbench.desktop.main.js:sourcemap:630  INFO [perf] Render performance baseline is 14ms
workbench.desktop.main.js:sourcemap:630  WARN Settings pattern "application.*" doesn't match any settings
```
So, I create the folder and then selecting "Add Note" added a comment in my ode and created the backing MD file but didn't open it. When I look in the console, I see this:


console.ts:137 [Extension Host] TypeError: Cannot destructure property 'ranges' of 'this.scanner.scanLine(...)' as it is undefined.
    at a.SidenoteFactory.build (c:\Users\chad\.vscode\extensions\cyberbiont.vscode-sidenotes-1.0.0\dist\extension.js:8:30620)
    at async a.DictionaryRepository.create (c:\Users\chad\.vscode\extensions\cyberbiont.vscode-sidenotes-1.0.0\dist\extension.js:8:27122)
    at async a.default.run (c:\Users\chad\.vscode\extensions\cyberbiont.vscode-sidenotes-1.0.0\dist\extension.js:8:934)
    at async r.h (p:\Users\chad\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:82736)



Let me know what else you need. If it is helpful to you, I am willing to do a Webex desktop share session with you to help you debug.

-Chad

**Comment by dokmanc** [comment]
I noticed that the ath reported in the error message, 
c:\Users\chad.vscode\extensions\
Seems like it was missing a backslash. The following folder is found on my machine:
C:\Users\chad\.vscode\extensions
